// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvqsckwghemnzfqtvruy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cXNja3dnaGVtbnpmcXR2cnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjY1MzYsImV4cCI6MjA2ODk0MjUzNn0.gwRO1dLn23NK4_u_EbraQSK67OqfhW0R3azO-60TDnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});